# Uncomment the next line to define a global platform for your project
 platform :ios, '7.0'

target 'JDragonHUDDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JDragonHUDDemo
pod 'JDragonHUD’, :path => '../JDragonHUD.podspec'  #指定podspec文件

  target 'JDragonHUDDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JDragonHUDDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
